### PR TITLE
[#116] Refactor extraction of last token from text

### LINKED ISSUE #116: Completion should work even when the prexif contains non whitespace chars
**Describe the bug**
When a line includes something other than whitespace characters in the line that are not the module name and the trigger `:`, the completion does not work.

**To Reproduce**
Write something like:
```
foo() ->
   X = erlang_ls_poi:
```
The options from completion will not show up.

**Expected behavior**
Exported functions from `erlang_ls_poi` (or whatever module typed in) should be returned.

**Actual behavior**
Options are not returned.

**Context**
 - `erlang_ls` version (tag/sha): `ba52457`
 - Editor used: Emacs
 - LSP client used: lsp-mode

### PR DESCRIPTION
**Pull request by robertoaloi**
### Description

* Move text manipulation functions to a separate module
* Use OTP library functions instead of custom pattern matching.

Fixes #116 .

### CODE REVIEW

File: src/erlang_ls_completion_provider.erl [hunk 1]
```diff
@@ -39,13 +39,14 @@ handle_request({completion, Params}, State) ->
    , <<"textDocument">> := #{<<"uri">> := Uri
                             }
    } = Params,
-  {ok, Document} = erlang_ls_db:find(documents, Uri),
+  {ok, #{text := Text}} = erlang_ls_db:find(documents, Uri),
```
Comment (jfacorro) [inline src/erlang_ls_completion_provider.erl]: I think this is breaking the opaqueness of the `document()` type. Why not use the `erlang_ls_document:text/1` function?

Comment (robertoaloi) [reply src/erlang_ls_completion_provider.erl]: Nice catch, will fix.

File: src/erlang_ls_completion_provider.erl [hunk 2]
```diff
@@ -58,10 +60,10 @@ handle_request({completion, Params}, State) ->
 -spec find_completion(binary(), binary(), binary()) ->
    any().
 find_completion(Prefix, ?TRIGGER_CHARACTER, <<":">>) ->
-  {ok, Tokens, _} = erl_scan:string(binary_to_list(Prefix)),
-  [{':', _}, Token | _] = lists:reverse(Tokens),
-  case Token of
-    {atom, _, Module} ->
+  Token = erlang_ls_text:last_token(Prefix),
+  case erl_syntax:type(Token) of
```
[the remark this answers is not in the document]
Comment (robertoaloi) [reply src/erlang_ls_completion_provider.erl]: I see. I still don't like to expose the internal format of the atom-tuple, though. I will try/catch instead.
