### PR TITLE
[Fixes #19] [Fixes #20] Shutdown request keep state

### LINKED ISSUE #19: Shutdown Request
The shutdown request is sent from the client to the server. It asks the server to shut down, but to not exit (otherwise the response might not be delivered correctly to the client). There is a separate exit notification that asks the server to exit.  Clients must not send any notifications other than exit or requests to a server to which they have sent a shutdown requests. If a server receives requests after a shutdown request those requests should be errored with `InvalidRequest`.

Request:

* method: `shutdown`
* params: `void`

Response:

* result: `null`
* error: code and message set in case an exception happens during shutdown request.

### LINKED ISSUE #20: Exit Notification
A notification to ask the server to exit its process. The server should exit with success code 0 if the shutdown request has been received before; otherwise with error code 1.

Notification:

* method: `exit`
* params: `void`

### PR DESCRIPTION
**Pull request by jfacorro**
### Description

Keep track of the status of the server so we can respond accordingly to requests after `shutdown` and `exit` with the correct exit code, following the protocol specifications.

Fixes #19. Fixes #20.

### CODE REVIEW

File: src/erlang_ls_utils.erl [hunk 1]
```diff
@@ -0,0 +1,7 @@
+-module(erlang_ls_utils).
```
Comment (robertoaloi) [inline src/erlang_ls_utils.erl]: Do we really need this?

File: test/prop_statem.erl [hunk 2]
```diff
@@ -155,6 +158,55 @@ did_close_post(_S, _Args, Res) ->
...
+  catch disconnect(),
+  S#{shutdown => false, connected => false}.
+
+exit_post(S, _Args, Res) ->
+  ExpectedExitCode = case maps:get(shutdown, S, false) of
+                       true  -> 0;
+                       false -> 1
+                     end,
+  wait_for(halt_called, 1000),
+  ?assert(meck:called(erlang_ls_utils, halt, [ExpectedExitCode])),
```
Comment (robertoaloi) [inline test/prop_statem.erl]: I see now why you wanted a wrapper around the halt function.

Comment (jfacorro) [reply test/prop_statem.erl]: Testing the usage of `erlang:exit/1` always ends up being a little convoluted.

**Comment by robertoaloi** [comment]
This was long due. Thanks!
