### PR TITLE
[#527] Add 'imported' flag to auto-imported built-in functions

### LINKED ISSUE #527: Highlighting information provides negative column
**Describe the bug**

Putting the cursor on `spawn` at line 28 of `els_text_synchronization.erl` results in incorrect highlighting of other usages of the identifier.

Screenshot 2020-03-06 at 10 25 58

The message returned from `erlang_ls` is

```json
[Trace - 10:22:14 am] Received response 'textDocument/documentHighlight - (77)' in 203ms.
Result: [
  {
    "range": {
      "start": {
        "line": 20,
        "character": -4
      },
      "end": {
        "line": 20,
        "character": 8
      }
    },
    "kind": 1
  },
  {
    "range": {
      "start": {
        "line": 27,
        "character": -4
      },
      "end": {
        "line": 27,
        "character": 8
      }
    },
    "kind": 1
  },
  {
    "range": {
      "start": {
        "line": 46,
        "character": 2
      },
      "end": {
        "line": 46,
        "character": 14
      }
    },
    "kind": 1
  }
]
```

**To Reproduce**

Open `erlang_ls/src/els_text_synchronization.erl`, place cursor.

**Expected behavior**

The highlights exactly match the occurrences of the symbol.

**Actual behavior**

The highlights start early and end late.

**Context**
 - `erlang_ls` version (tag/sha): a5149fc89abaf9c98846dac57993940384697044
 - Editor used: emacs
 - LSP client used: lsp-mode

### PR DESCRIPTION
**Pull request by jfacorro**
### Description

Add 'imported' flag to auto-imported built-in functions.

Fixes #527.

### CODE REVIEW

File: src/els_parser.erl [hunk 1]
```diff
@@ -181,22 +181,29 @@ do_points_of_interest(Tree, EndLocation) ->
...
+        %% Local call
+        false -> [poi(Pos, application, {F, A})]
+      end;
+    MFA ->
+      [poi(erl_syntax:get_pos(Tree), application, MFA)]
   end.
 
+-spec is_erlang_bif(atom(), arity()) -> boolean().
+is_erlang_bif(F, A) ->
+  lists:member({F, A}, erlang:module_info(exports)).
```
Comment (michalmuskala) [inline src/els_parser.erl]: This is not 100% accurate. Not all functions in the `erlang` module are automatically imported. We probably should use [`erl_internal:bif/2`](https://erlang.org/doc/man/erl_internal.html#bif-2) here

Comment (robertoaloi) [reply src/els_parser.erl]: Created #633 as a follow-up.
