### PR TITLE
[#1047] Mark headers with compiler attributes as used

### LINKED ISSUE #964: Do not mark includes as unused if they contain module attributes
**Describe the bug**
The `unused_includes` diagnostic reports include files unused even if they contain module attributes, such as `-compile` directives. E.g. `-include_lib("stdlib/include/ms_transform.hrl").` will always be reported as unused, but removing it would disable an important parse transform.

**Context**
 - `erlang_ls` version (tag/sha): 0.13.0
 - Editor used: VS Code

### PR DESCRIPTION
**Pull request by robertoaloi**
### Description

Fixes #964 and partially #1047.

### CODE REVIEW

File: apps/els_lsp/src/els_unused_includes_diagnostics.erl [hunk 1]
```diff
@@ -120,3 +121,31 @@ inclusion_range(Uri, Document) ->
     _ ->
       #{from => {1, 1}, to => {2, 1}}
   end.
+
+%% @doc Given a list of included uris, filter out the ones containing
+%% compiler attributes. If the Uri cannot be found, keep it in the list.
```
Comment (gomoripeti) [inline apps/els_lsp/src/els_unused_includes_diagnostics.erl:126]: to me it looks like if lookup_document fails the Uri is filtered out.

**Review by gomoripeti — APPROVED** [review]

File: apps/els_lsp/src/els_unused_includes_diagnostics.erl (hunk 1 above)
Comment (robertoaloi) [reply apps/els_lsp/src/els_unused_includes_diagnostics.erl:126]: Nice catch. Fixed (the code, not the comment).
