### PR TITLE
Make els_code_navigation find non-fully qualified BIFs

### LINKED ISSUE #860: "fun atom_to_list/1" not found by crossref
**Describe the bug**

```erlang
    S = fun atom_to_list/1,
    S = fun erlang:atom_to_list/1,
```

The `crossref` diagnostics report a "not found" error for the first occurrence of `atom_to_list`, not the second.

**Context**
 - `erlang_ls` version (tag/sha): 90a68d8b40138ba06402c17699aa079e1593fcad
 - Editor used:
 - LSP client used:

### PR DESCRIPTION
**Pull request by al-khanji**
### Make els_code_navigation find non-fully qualified BIFs

Add indexing of no_auto_import compile options. Use this information when deciding whether a fun reference is to a BIF.

Fixes #860.

### CODE REVIEW

**Comment by al-khanji** [comment]
Need to add tests, hence a draft.

File: src/els_code_navigation.erl [hunk 1]
```diff
@@ -74,6 +86,55 @@ goto_definition(_Uri, #{ kind := parse_transform, id := Module }) ->
...
+  case {OldBif, Bif} of
+    %% Cannot be shadowed, always imported
+    {true, true} ->
+      true;
+    %% It's not a BIF at all
+    {false, false} ->
+      false;
+    %% The hard case
+    {_, _} ->
+      is_bif_auto_import_disabled(Uri, F, A)
```
Comment (gomoripeti) [inline src/els_code_navigation.erl:102]: my personal opinion (but I am not an erlang_ls maintainer) is that you don't need to check if auto_import is disabled, just jump to the bif at this point
- it can be disabled also in a header file, or rebar.config or erlc command line option of which erlang_ls might not even know
- auto_import is usually disabled to silence warnings about a bif clashing with a local function - but at this point no local function is found so it is highly likely there won't be a no_auto_import directive

what I mean is that this algorithm can not be 100% correct (because erlang_ls does not have all the info) so instead let's use a simple heuristic that already covers most of the practical cases (and also not 100% correct)

btw very nice thorough code covering all the edge cases

**Comment by robertoaloi** [comment]
@al-khanji This PR is still marked as a _draft_. Let me know when you want me to have a look.

**Comment by al-khanji** [comment]
> @al-khanji This PR is still marked as a _draft_. Let me know when you want me to have a look.

When you get a chance please take a look, I dropped POI parsing and just check whether we find a bif of any sort.

**Review by gomoripeti — APPROVED** [review]
very nice!

**Comment by robertoaloi** [comment]
Thanks!
