### PR TITLE
Fix docs for macro with arguments

### LINKED ISSUE #1022: Get macro name error in docs
**Describe the bug**
#1008
https://github.com/erlang-ls/erlang_ls/blob/28694b75a168d60e5f80ff014c7f3f36978948aa/apps/els_lsp/src/els_parser.erl#L659-L660
https://github.com/erlang-ls/erlang_ls/blob/28694b75a168d60e5f80ff014c7f3f36978948aa/apps/els_lsp/src/els_docs.erl#L51-L55

The `Name` on line 54 may be a tuple. Using `atom_ to_ list` can cause crash.

**To Reproduce**

```erlang
-module(test).
-export([test/0]).

-define(TEST(_), 1).

test() ->
  %% hover in this marco
  ?TEST(_),
  ok.
```

**Expected behavior**
image

**Actual behavior**
image

**Log**

```erlang
[2021-05-27T09:29:27.732000+08:00] gen_server.erl:889 <0.161.0> [error] ** Generic server els_hover_provider terminating , ** Last message in was {handle_request,{hover,#{<<"position">> => #{<<"character">> => 6,<<"line">> => 11},<<"textDocument">> => #{<<"uri">> => <<"file:///c%3A/Users/miSaki/Desktop/test/src/test.erl">>}}}}, ** When Server state == #{internal_state => #{},provider => els_hover_provider}, ** Reason for termination ==, ** {badarg,[{erlang,atom_to_list,[{'TEST',1}],[]},{els_docs,docs,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_docs.erl"},{line,54}]},{els_hover_provider,get_docs,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_hover_provider.erl"},{line,41}]},{els_hover_provider,handle_request,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_hover_provider.erl"},{line,35}]},{els_provider,handle_call,3,[{file,"d:/erlang_ls/apps/els_core/src/els_provider.erl"},{line,92}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}, ** Client els_server stacktrace, ** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,219}]},{els_methods,textdocument_hover,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_methods.erl"},{line,234}]},{els_methods,dispatch,4,[{file,"d:/erlang_ls/apps/els_lsp/src/els_methods.erl"},{line,71}]},{els_server,handle_request,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_server.erl"},{line,165}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{els_server,handle_cast,2,[{file,"d:/erlang_ls/apps/els_lsp/src/els_server.erl"},{line,121}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]}]
```

**Context**
 - `erlang_ls` version (tag/sha): main
 - Editor used: VSCode 1.56.2
 - LSP client used: erlang-ls.erlang-ls

### PR DESCRIPTION
**Pull request by gomoripeti**
Fixes #1022

### CODE REVIEW

File: apps/els_lsp/src/els_docs.erl [hunk 1]
```diff
@@ -50,8 +50,8 @@ docs(Uri, #{kind := Kind, id := {F, A}})
   function_docs('local', M, F, A);
 docs(Uri, #{kind := macro, id := Name} = POI) ->
   case els_code_navigation:goto_definition(Uri, POI) of
-    {ok, DefUri, #{data := #{value_range := ValueRange}}} ->
-      NameStr = atom_to_list(Name),
+    {ok, DefUri, #{data := #{args := Args, value_range := ValueRange}}} ->
+      NameStr = macro_signiture(Name, Args),
```
Comment (robertoaloi) [inline apps/els_lsp/src/els_docs.erl:54]: Did you mean "signature"?

Comment (gomoripeti) [reply apps/els_lsp/src/els_docs.erl:54]: oh indeed :)

**Comment by robertoaloi** [comment]
Thanks!
