### PR TITLE
Handle macros in type attributes

### LINKED ISSUE #908: Macros in -spec and -type crashing indexer
**Describe the bug**
Having 
```
-spec from_boolean(Boolean :: boolean()) ->
  Binary :: ?fix_binary(8).

-type url() :: ?fix_binary(8, 8).
```

Resulting:
```
[2021-02-12T10:05:41.197089+01:00] /Users/zsoci/Projects/erlang_ls/apps/els_lsp/src/els_methods.erl:143 <0.186.0> [info] initialized: [App=els_lsp] [Version="0.9.0+build.1405.refa5db18d"]
[2021-02-12T10:05:41.266162+01:00] /Users/zsoci/Projects/erlang_ls/apps/els_lsp/src/els_methods.erl:74 <0.186.0> [error] Unexpected error [type=error] [error={badarg,{tree,macro,{attr,0,[],none},{macro,{tree,variable,{attr,0,[],none},'NO_TX_INFO'},none}}}] [stack=[{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7330}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7285}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7282}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7283}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]}]]
[2021-02-12T10:05:41.339903+01:00] /Users/zsoci/Projects/erlang_ls/apps/els_lsp/src/els_indexing.erl:136 <0.199.0> [error] Error indexing file [filename=/Users/zsoci/Projects/rta/apps/ali/src/ali_account_actor.erl, uri=file:///Users/zsoci/Projects/rta/apps/ali/src/ali_account_actor.erl] error:{badarg,{tree,macro,{attr,0,[],none},{macro,{tree,atom,{attr,0,[],none},'<macro> ('},none}}}:[{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7330}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7285}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7282}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7285}]}]
[2021-02-12T10:05:41.356009+01:00] /Users/zsoci/Projects/erlang_ls/apps/els_lsp/src/els_indexing.erl:136 <0.199.0> [error] Error indexing file [filename=/Users/zsoci/Projects/rta/apps/rta_common/src/rta_util.erl, uri=file:///Users/zsoci/Projects/rta/apps/rta_common/src/rta_util.erl] error:{badarg,{tree,macro,{attr,0,[],none},{macro,{tree,atom,{attr,0,[],none},'<macro> ('},none}}}:[{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7330}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7285}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7282}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete_list,1,[{file,"erl_syntax.erl"},{line,7334}]},{erl_syntax,concrete,1,[{file,"erl_syntax.erl"},{line,7285}]}]
```

**To Reproduce**
This is introduced by the following two commits:
a5db18dd38ef126857e0252693678de61f4bfd53
48c14cbe8170eb832c1ca48f6b0db355fdf0085e

**Actual behavior**
indexer also crashes so code navigation does not work.

### PR DESCRIPTION
**Pull request by gomoripeti**
### Description

`erl_syntax:attribute_arguments` returns the AST of AST for type attributes. (See details in code comments) That is problematic in multiple places:
- `els_dodger` can't properly find and rewrite magic-macro-tuples because it will see the AST of the AST of these tuples. It still used to add fallback macros.
- then `erl_syntax:concrete` only handles an AST of a term, it crashes if the input includes AST of macros (or types). [`erl_syntax_lib:analyze_wild_attribute` ](https://github.com/erlang/otp/blob/master/lib/syntax_tools/src/erl_syntax_lib.erl#L1604) uses that and also fails.

Because els forked the dodger we have the freedom to return different representation for type attributes. But that needs to be handled in els_parser as well.
New representation of args are: ([erl_parse abstract format](http://erlang.org/doc/apps/erts/absform.html#module-declarations-and-forms) for reference)
- callback, spec: erl_parse `{{Name,Arity},[AST(fun_type), ...]}` => els_dodger `AST({Name, Arity}, [fun_type, ...]}`
- type, opaque: erl_parse `{Name,AST(type),[AST(var), ..]}` => els_dodger `AST({Name, type, [var, ...]})`

Fixes #908

### TODO

- [ ] more macro tests

### CODE REVIEW

File: apps/els_lsp/src/els_parser.erl [hunk 1]
```diff
@@ -111,6 +111,37 @@ find_attribute_pois(Tree, Tokens) ->
       []
   end.
 
+%% @doc Analyze an attribute node with special handling for type attributes.
+%%
+%% `erl_syntax_lib:analyze_attribute` can't handle macros in wild attribute
+%% arguments. It also handles `callback', `spec', `type' and `opaque' as wild
+%% attributes. Therefore `els_dodger' has to handle these forms specially and
+%% here we have to adopt to the different output of `els_dodger'.
```
Comment (robertoaloi) [inline apps/els_lsp/src/els_parser.erl:119]: Nit: adopt -> adapt

**Review by robertoaloi — APPROVED** [review]

**Comment by robertoaloi** [comment]
🥇

**Comment by robertoaloi** [comment]
Thanks!
