### PR TITLE
[#641] do not report xref errors for pseudo functions

### LINKED ISSUE #641: xref cannot find record_info
**Describe the bug**

If a module uses `record_info`, the XRef diagnostics reports an error that the function `record_info/2` cannot be found.

According to the [docs](http://erlang.org/doc/reference_manual/records.html)

> To each module using records, a pseudo function is added during compilation to obtain information about records:
>
>`    record_info(fields, Record) -> [Field]`
>`     record_info(size, Record) -> Size`
>
> Size is the size of the tuple representation, that is, one more than the number of fields.

**To Reproduce**

Open a module using `record_info`

**Context**
 - `erlang_ls` version (tag/sha): 7ad7adb1a82b255f9cd947af2083b871ab5cac30
 - Editor used:
 - LSP client used:

### LINKED ISSUE #644: xref cannot find lager:xxx
**Describe the bug**

The xref diagnostics report on functions that do not have a definition.

`lager` uses a parse_transform to convert calls such as `lager:info("foo")` into
 something appropriate.  But the xref processing does not know about this, and
 so reports an error because it cannot resolve the reference.

**To Reproduce**

Open a file with a lager logging call in it.

**Expected behavior**

No xref warning for the lager call

**Actual behavior**

The lager call generates an xref error saying it s not defined.

**Context**
 - `erlang_ls` version (tag/sha): 6d0d808ba9804c2e85d5793d620717175821f9f4
 - Editor used:
 - LSP client used:

### PR DESCRIPTION
**Pull request by alanz**
The functions

    record_info/2
    module_info/0
    module_info/1

are pseudo functions generated and processed by the erlang compiler. Do not
report xref errors if they are encountered, as they are always valid.

Closes #641.
Closes #644.

### CODE REVIEW

File: src/els_xref_diagnostics.erl [hunk 1]
```diff
@@ -62,6 +62,12 @@ make_diagnostic(#{range := Range, id := Id}) ->
                                  , source()).
 
 -spec has_definition(poi(), els_dt_document:item()) -> boolean().
+has_definition(#{ kind := application
+                , id := {erlang, module_info, 0} }, _) -> true;
+has_definition(#{ kind := application
+                , id := {erlang, module_info, 1} }, _) -> true;
```
Comment (michalmuskala) [inline src/els_xref_diagnostics.erl:68]: This seems wrong. Those functions are not defined on the erlang module. Why would they show up like this in here?

Comment (alanz) [reply src/els_xref_diagnostics.erl:68]: Empirical testing, I logged what I got when I opened files with the issue.

And it *does* work with this match.

Comment (michalmuskala) [reply src/els_xref_diagnostics.erl:68]: I wonder if it's related to this https://github.com/erlang-ls/erlang_ls/issues/633 - since those functions also exist on the `erlang` module

Comment (robertoaloi) [reply src/els_xref_diagnostics.erl:68]: The `module_info/0,1` functions are special and inserted by the compiler to **all** modules, not just the `erlang` one:

https://erlang.org/doc/reference_manual/modules.html#module_info-0-and-module_info-1-functions

I suggest we hold on for this one and instead focus on #621 , which will make this not needed.

**Comment by robertoaloi** [comment]
@alanz should we close this one for now and focus on the build server / real xref? We can eventually re-open it later, keep the branch.

**Comment by alanz** [comment]
Re-opening, to be able to use this feature on code with `record_info` in it.

**Comment by michalmuskala** [comment]
Given https://github.com/erlang-ls/erlang_ls/issues/633 is solved, we probably need `{module_info, _}` rather than `{erlang, module_info, _}` included

**Comment by alanz** [comment]
> Given #633 is solved, we probably need {module_info, _} rather than {erlang, module_info, _} included

I just confirmed that by running it manually. Will update the tests to catch it too.

**Review by robertoaloi — APPROVED** [review]
