### PR TITLE
[#518] Replace group leader when using stdio transport

### LINKED ISSUE #518: Restrict the processes that can write to standard output when using stdio transport
**Describe the bug**
There are some external dependencies that are sometimes writing to `stdout` to report warning or errors. If the server is communicating through `stdio` the intervention of these dependencies corrupt the messages and some clients start failing completely.

**To Reproduce**
Create a module `foo` that has a duplicated type spec like the following:

```erlang
-module(foo).
-export([baz/0]).
-type bar() :: atom().
-type bar() :: atom().

-spec baz() -> bar().
baz() -> ok.
```

Call `foo:baz()` from some other module and hover over the function call. 

In VS Code this will cause the client to stop being able to process any response from the server. Opening the deveoper tools (i.e. `Cmd+Shift+P -> Developer: Toogle Developer Tools`) will show one or more instances of the following error: `Error: Header must provide a Content-Length property.`.

In Emacs this isn't failing, I suspect it's because the client is more forgiving and is somehow able to recover from the cocrrupted messages.

**Expected behavior**
Nothing other that `els_stdio` should be able to write to standard output.

**Actual behavior**
Some clients (e.g. VS Code) stop working when something else writes to standard output.

**Context**
 - `erlang_ls` version (tag/sha): `0.1.0-49-g134838a`
 - Editor used: `VS Code 1.42.0`
 - LSP client used: `Erlang LS 0.0.9`

### PR DESCRIPTION
**Pull request by jfacorro**
### Description

Replace group leader when using stdio transport.

Fixes #518.

### CODE REVIEW

**Comment by jfacorro** [comment]
> I saw in reading that the group leader is abused to harvest processes when shutting down. Will that be compromised by this?

I don't think it will. The processes that wouldn't be killed are the ones that are not under the supervision tree, as long as every process we spawn is linked to a process in the supervision tree it should be fine.

> Will it matter, given we shut down the O/S process as a whole when terminating the server?

I agree that it ultimately does not matter for the users. If by any chance some dangling process is still alive when the application is stopped, this could affect some of the tests, depending on what the process does. But this would still happen without this change in the PR, @robertoaloi was having some issues with the process that keeps the TCP connection in his indexing PR.

**Comment by alanz** [comment]
Running this under emacs, I get

```
LSP :: Connected to [erlang-ls:14246 status:starting].
LSP :: erlang-ls:14246 initialized successfully
Error processing message (lsp-unknown-message-type #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("error" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("code" -32001 "message" "Unexpected error while initialized")) "id" nil "jsonrpc" "2.0"))).
```

Bisecting blames 9050e6a4c8c6e6fbd2ecd13a13755cdffe27c308

**Comment by robertoaloi** [comment]
If possible, I would appreciate @dszoboszlay 's input on this one.

**Comment by alanz** [comment]
BTW, the error in emacs is complaining about this line getting hit

https://github.com/erlang-ls/erlang_ls/blob/9050e6a4c8c6e6fbd2ecd13a13755cdffe27c308/src/els_methods.erl#L73

**Comment by alanz** [comment]
My setup is mac, catalina, emacs `GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02`

`Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
`

**Comment by jfacorro** [comment]
I found the problem! We are using `application:get_application()` which is relying on the `group_leader()`:
```
-spec get_application() -> 'undefined' | {'ok', Application} when
      Application :: atom().
get_application() -> 
    application_controller:get_application(group_leader()).
```

File: src/els_sup.erl [hunk 1]
```diff
@@ -40,6 +40,8 @@ init([]) ->
               , period    => 60
               },
   {ok, Transport} = application:get_env(erlang_ls, transport),
+  %% Restrict access to stdio when using that transport
+  (Transport =/= els_stdio) andalso restrict_stdio_access(),
```
Comment (dszoboszlay) [inline src/els_sup.erl]: Isn't this the opposite of what you want? You call `restrict_stdio_access()` for every transport _except for_ `els_stdio`.

Comment (robertoaloi) [reply src/els_sup.erl]: It looks like @dszoboszlay is correct. I also suggest we do not rely on the `andalso` semantics for this, since it makes the code less readable. I would rather:

```
restrict_stdio_access(els_stdio) ->
  restrict_stdio_access();
restrict_stdio_access(_) ->
  ok.
```

**Comment by dszoboszlay** [comment]
All in all, I don't think you should base your solution on changing the `group_leader` in one supervisor.

* It prevents `application:get_application()` from working properly.
* If you start a different application with a supervisor tree, this solution will not block that application's processes from writing to the standard output.

I'd recommend taking a completely different approach:

* Start Erlang with the `-nouser` command line argument. This will tell the `kernel` not to start a `user` process, basically blocking access to the `standard_io` I/O device.
* You can still access the standard output of the OS process by opening `{fd, 0, 1}` as a port:

```erlang
P = erlang:open_port({fd, 0, 1}, []),
erlang:port_command(P, <<"hello world!\n">>),
erlang:port_close(P).
```

It is very unlikely that any other library would accidentally write to this port! :smile:

File: src/els_sup.erl (hunk 1 above)
Comment (jfacorro) [reply src/els_sup.erl]: 🤦

Comment (jfacorro) [reply src/els_sup.erl]: #532 532
