### PR TITLE
[1371] Add Custom Hostname and Domain Options

### LINKED ISSUE #1371: Need Custom Node Name / Host Name / Domain Name
I need the ability to set a custom hostname/domain name, especially when long names are used.  

Currently, the code gets the hostname from `inet` module in the code below.

https://github.com/erlang-ls/erlang_ls/blob/2dfb48aca3879e5b44f6fd676f8349525262779f/apps/els_core/src/els_distribution_server.erl#L226-L227

Additionally, if `longnames` are used, then the following code also looks for a domain name:

https://github.com/erlang-ls/erlang_ls/blob/6ec94072f5b9bb984da1026f9ba0efaa072271b7/apps/els_core/src/els_distribution_server.erl#L232-L234

---

If there is no domain set, then a `.` (Dot) is added to the end of the default system hostname.  This can be seen in the server log:

```log
 [info] Distribution enabled [name='erlang_ls_couchdb_101062988@couchdbasdf.'] [els_distribution_server:start_distribution/4 L81] <0.147.0>
 [info] Started distribution for: ['erlang_ls_couchdb_101062988@couchdbasdf.'] [els_general_provider:handle_request/1 L94] <0.147.0>
```

 This results in broken commucation between the nodes, for example:

```bash
root@couchdbasdf:/workspaces/couchdb# epmd -names
epmd: up and running on port 4369 with data:
name remsh3950 at port 35375
name node3 at port 37055
name node1 at port 45007
name node2 at port 43553
name erlang_ls_dap_couchdb_61071580 at port 33395
name erlang_ls_couchdb_101062988 at port 42991

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988@couchdbasdf.
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***

----- OR Without the Dot at the end ------

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988@couchdbasdf 
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***
=ERROR REPORT==== 28-Aug-2022::23:51:43.999881 ===
** System running to use fully qualified hostnames **
** Hostname couchdbasdf is illegal **

----- OR without the hostname entirely -----

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988             
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***

----- OR From the project node ------

Eshell V13.0.4  (abort with ^G)
(node1@127.0.0.1)1> net_adm:ping('erlang_ls_couchdb_101062988@couchdbasdf.').
pang
(node1@127.0.0.1)2> net_adm:ping('erlang_ls_couchdb_101062988@couchdbasdf'). 
pang
(node1@127.0.0.1)3> net_adm:ping('erlang_ls_couchdb_101062988').            
pang
(node1@127.0.0.1)4> 
```

Because of the above, I have to do some really hacky things to get my setup to work.

Current Setup:
- VSCode
- DevContainer (in Docker)
- Erlang Ls extension
- Apache/CouchDB codebase

The CouchDB code base has a boot strap type dev script that spins up a cluster with 3 nodes that are named `node{1-3}@127.0.0.1` using longnames.  This can be seen in the output of `epmd -names` shown above.

In order to get communication between nodes, code_reloading and debugging to work I have to set the hostname to `127` and include an `erl_inetrc` file that contains the following:

```erlang
%% -- ERLANG INET CONFIGURATION FILE --
{domain, "0.0.1"}.
```

My erlang_ls.config file looks like this:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127"   # <-- the ".0.0.1" gets added by els_utils:compose_node_name because of using longnames
runtime:
    use_long_names: true
```

My `launch.json` file looks like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start Dev w/ Debug",
            "use_long_names": true,
            "type": "erlang",
            "request": "launch",
            "runinterminal": [
                "./dev/run",
                "--with-admin-party-please",
                "--no-eval",
                "dev/remsh"
            ],
            "projectnode": "node1@127.0.0.1",
            "timeout": 300,
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

---

# Proposal

I believe all this heart ache could be relieved if there was a custom `hostname` option for the `erlang_ls.config` file.

Additionally, I am curious if it is truly intended for the `code_reload: node:` setting to be modified at all?  It seems more natural to specify exactly the node to connect to for code reloading than to have to remember that the hostname/domain will get appended.  Is there a reason the code looks at the node name and modifies it?

For example:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127.0.0.1"   <--- remove the code that modifies this node name in els_utils:compose_node_name
runtime:
    use_long_names: true
hostname: "127.0.0.1"
```

and then update the `els_distribution_server` with something like this?

```diff
node_name(Prefix, Name0) ->
+   CustomHostname = els_config:get(hostname),
+   case CustomHostname of
+       undefined ->
            Name = normalize_node_name(Name0),
            Int = erlang:phash2(erlang:timestamp()),
            Id = lists:flatten(io_lib:format("~s_~s_~p", [Prefix, Name, Int])),
            {ok, HostName} = inet:gethostname(),
            node_name(Id, HostName, els_config_runtime:get_name_type());
+       _ -> CustomHostname
+   end.
```

Those more familiar with this project and code base may know more and be able to offer better suggestions/thoughts/feedback.

Thank you.

### PR DESCRIPTION
**Pull request by zachlankton**
# #1371  Add Custom Hostname and Domain Options

When using `longnames` in projects that don't adhere to the host-provided hostname and domain it is useful to be able to override those via the `erlang_ls.config` file.  The code in this commit provides these options as well as cleans up some related duplicated code.

This code also fixes a small bug that would leave a trailing dot `.` if a domain is not defined.

Tests have been updated to reflect these changes and new tests have been created to test the new options.

A sample config file with the new options looks like this:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127.0.0.1"
runtime:
    use_long_names: true
    hostname: "127"
    domain: "0.0.1"
```

The above is an exaggerated example, a simple, more direct one that accomplishes the same would be:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127.0.0.1"
runtime:
    use_long_names: true
    hostname: "127.0.0.1"
    # no need to also specify domain, but may be useful to override as an empty string if needed
    domain: ""
```

Fixes #1371

### CODE REVIEW

File: apps/els_core/src/els_config_runtime.erl [hunk 1]
```diff
@@ -31,6 +35,17 @@ get_node_name() ->
     Value = maps:get("node_name", els_config:get(runtime), default_node_name()),
     els_utils:compose_node_name(Value, get_name_type()).
 
+-spec get_hostname() -> string().
+get_hostname() ->
+    case els_config:get(runtime) of
+        undefined -> default_hostname();
+        Runtime -> maps:get("hostname", Runtime, default_hostname())
+    end.
```
Comment (zachlankton) [inline apps/els_core/src/els_config_runtime.erl:43]: We want the `get_node_name` function to be able to use `get_hostname` but when the `els_config` module initializes this value is not ready yet, so we need to check for `undefined` here and allow it pass otherwise.

File: apps/els_core/src/els_distribution_server.erl [hunk 2]
```diff
@@ -223,15 +222,7 @@ node_name(Prefix, Name0) ->
...
     Id = lists:flatten(io_lib:format("~s_~s_~p", [Prefix, Name, Int])),
-    {ok, HostName} = inet:gethostname(),
-    node_name(Id, HostName, els_config_runtime:get_name_type()).
-
--spec node_name(string(), string(), 'longnames' | 'shortnames') -> atom().
-node_name(Id, HostName, shortnames) ->
-    list_to_atom(Id ++ "@" ++ HostName);
-node_name(Id, HostName, longnames) ->
-    Domain = proplists:get_value(domain, inet:get_rc(), ""),
-    list_to_atom(Id ++ "@" ++ HostName ++ "." ++ Domain).
```
Comment (zachlankton) [inline apps/els_core/src/els_distribution_server.erl:234]: This code is duplicated and handled in `els_utils:compose_node_name`

File: apps/els_core/src/els_utils.erl [hunk 3]
```diff
@@ -453,15 +453,18 @@ compose_node_name(Name, Type) ->
             true ->
                 Name;
             _ ->
-                {ok, HostName} = inet:gethostname(),
+                HostName = els_config_runtime:get_hostname(),
```
Comment (zachlankton) [inline apps/els_core/src/els_utils.erl:456]: Replaced the `inet:gethostname()` with `els_config_runtime:get_hostname()` in all the relevant places in the code base.

File: apps/els_core/src/els_utils.erl [hunk 4]
```diff
@@ -453,15 +453,18 @@ compose_node_name(Name, Type) ->
...
         shortnames ->
             list_to_atom(NodeName);
         longnames ->
-            Domain = proplists:get_value(domain, inet:get_rc(), ""),
-            list_to_atom(NodeName ++ "." ++ Domain)
+            Domain = els_config_runtime:get_domain(),
+            case Domain of
+                "" -> list_to_atom(NodeName);
+                _ -> list_to_atom(NodeName ++ "." ++ Domain)
+            end
```
Comment (zachlankton) [inline apps/els_core/src/els_utils.erl:467]: This fixes the trailing dot `.` bug when `domain` is not defined.

File: apps/els_dap/src/els_dap_general_provider.erl [hunk 5]
```diff
@@ -1023,22 +1023,6 @@ safe_eval(ProjectNode, Debugged, Expression, Update) ->
...
-            {ok, HostName} = inet:gethostname(),
-            BinHostName = list_to_binary(HostName),
-            DomainStr = proplists:get_value(domain, inet:get_rc(), ""),
-            Domain = list_to_binary(DomainStr),
-            BinName = <<ProjectNode/binary, "@", BinHostName/binary, ".", Domain/binary>>,
-            binary_to_atom(BinName, utf8);
-        _ ->
-            binary_to_atom(ProjectNode, utf8)
-    end.
-
```
Comment (zachlankton) [inline apps/els_dap/src/els_dap_general_provider.erl:1041]: This code is duplicated and handled in `els_utils:compose_node_name`

File: apps/els_dap/src/els_dap_general_provider.erl [hunk 6]
```diff
@@ -1062,23 +1046,21 @@ start_distribution(Params) ->
...
+    ConfProjectNode = els_utils:compose_node_name(ConfProjectNode0, NameType),
+    ?LOG_INFO("Configured Project Node Name: ~p", [ConfProjectNode]),
+    Cookie = binary_to_atom(ConfCookie, utf8),
+
     %% start distribution
-    Prefix = <<"erlang_ls_dap">>,
-    Int = erlang:phash2(erlang:timestamp()),
-    Id = lists:flatten(io_lib:format("~s_~s_~p", [Prefix, Name, Int])),
-    {ok, HostName} = inet:gethostname(),
-    LocalNode = els_distribution_server:node_name(Id, HostName, NameType),
```
Comment (zachlankton) [inline apps/els_dap/src/els_dap_general_provider.erl:1081]: This code is duplicated and handled in `els_distribution_server:node_name`

File: apps/els_lsp/test/els_diagnostics_SUITE.erl [hunk 7]
```diff
@@ -626,12 +644,30 @@ code_path_extra_dirs(_Config) ->
...
+    ok.
+
+-spec use_long_names_no_domain(config()) -> ok.
+use_long_names_no_domain(_Config) ->
+    HostName = els_config_runtime:get_hostname(),
+    NodeName =
+        "my_node@" ++ HostName,
+    Node = list_to_atom(NodeName),
+    ?assertMatch(Node, els_config_runtime:get_node_name()),
+    ok.
```
Comment (zachlankton) [inline apps/els_lsp/test/els_diagnostics_SUITE.erl:663]: This test ensures that the trailing dot `.` problem should not be allowed.

**Comment by zsoci** [comment]
Seems to be OK for me.

**Comment by zachlankton** [comment]
Today I tested this PR on Ubuntu with Emacs and was able to use the custom `hostname: 127.0.0.1` with `use_long_names: true` to connect to the CouchDB dev node: `node1@127.0.0.1`.  Code reloading works and debugging works!

I have also tested this on Windows using VSCode and a devcontainer... also working well!

**Comment by robertoaloi** [comment]
Amazing! Thank you so much for this! 🚀
