### PR TITLE
[#478] Elvis diagnostics fail

### LINKED ISSUE #478: Elvis diagnostics fail for files not belonging to the project
When an OTP file is accessed (e.g. `gen_server`), the server starts calculating diagnostics for it. Elvis diagnostics assume the file is under the same project root directory, which is not true. Therefore, we get a `badmatch`:

     <<RootUri:RootUriSize/binary, RelativePath/binary>> = Uri

```
2020-02-26 08:08:23.899 [error] emulator Error in process <0.1405.0> on node 'erlang_ls_9e94b2f57e580c842c18e0a75dc0820c0f28498a@ws-6fd7bf2f-551b-4644-a930-aa07f7a8860c' with exit value:
{{badmatch,<<"file:///usr/local/lib/erlang/lib/stdlib-3.11.2/src/gen_server.erl">>},[{els_utils,project_relative,1,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_utils.erl"},{line,95}]},{els_elvis_diagnostics,diagnostics,1,[{
file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_elvis_diagnostics.erl"},{line,28}]},{els_text_synchronization,generate_diagnostics,1,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_text_synchronization.e
rl"},{line,40}]}]}
```

### PR DESCRIPTION
**Pull request by jfacorro**
### Description

When using `els_utils:project_relative/1` handle the case when the URI is not relative to the root URI.

Fixes #478.

### CODE REVIEW

File: src/els_compiler_diagnostics.erl [hunk 1]
```diff
@@ -121,7 +121,7 @@ diagnostic(_Path, MessagePath, Range, Document, Module, Desc0, Severity) ->
   InclusionRange = inclusion_range(MessagePath, Document),
   %% The compiler message is related to an included file. Replace the
   %% original location with the location of the file inclusion.
-  Desc = io_lib:format("Issue in included file (~p): ~s", [Line, Desc0]),
+  Desc = io_lib:format("Issue in included file (~p): ~p", [Line, Desc0]),
```
Comment (jfacorro) [inline src/els_compiler_diagnostics.erl]: Description is not always a string.
