### PR TITLE
Fix issues with rename variable involving specs

### LINKED ISSUE #1180: Rename on a variable renames variables in a following spec
**Describe the bug**
Given this code:
```erl
foo(A) -> A.

-spec bar(A :: integer()) -> integer().
bar(A) -> A.
```
Using the "Rename" command with text "B" on either of the `A` variables in `foo` produces:
```erl
foo(B) -> B.

-spec bar(B :: integer()) -> integer().
bar(A) -> A.
```

**Expected behavior**

It should not touch the spec and produce:
```erl
foo(B) -> B.

-spec bar(A :: integer()) -> integer().
bar(A) -> A.
```

**Context**
 - `erlang_ls` version (tag/sha): Last release (Erlang LS (in erlang_ls), version: 0.21.2, OTP version: 24)
 - Editor used: VS Code

### PR DESCRIPTION
**Pull request by plux**
### Description

Tweak the heuristic for variable renaming inside functions so it doesn't bleed over to following -spec.
Add possibility to rename variables in specs.

Fixes #1180.

### CODE REVIEW

File: apps/els_lsp/src/els_rename_provider.erl [hunk 1]
```diff
@@ -222,18 +222,29 @@ new_name(_, NewName) ->
...
-         end,
-  %% Find beginning of first function clause after VarRange
-  To = case [R || #{range := R} <- FunPOIs, els_range:compare(VarRange, R)] of
-        []                 -> {999999999, 999999999}; % End of document
-        [#{from := End}|_] -> End
-       end,
-  #{from => From, to => To}.
+  POIs = els_poi:sort(els_dt_document:pois(Document, [ function_clause
+                                                     , spec
+                                                     ])),
```
Comment (michalmuskala) [inline apps/els_lsp/src/els_rename_provider.erl:227]: This should probably consider all possible top-level forms. I haven't checked, but I'd imagine similar issue will happen with things like:
```
foo(A) -> A.
-define(?MACRO(A), A).
```
and other top-level items (like `-callback` and `-type`).

TBH, I'm not sure why the logic tries to look for the beginning point of the next form. Wouldn't it be enough to look for the end point of the current clause?

Comment (robertoaloi) [reply apps/els_lsp/src/els_rename_provider.erl:227]: If I remember correctly, it's to ensure renaming works even when the current clause is not fully parsable (still being written).

File: apps/els_lsp/src/els_rename_provider.erl [hunk 2]
```diff
@@ -222,18 +222,29 @@ new_name(_, NewName) ->
...
+      SpecRange;
+    [] ->
+      %% Find beginning of first function clause before VarRange
+      From =
+        case [R || #{range := R} <- POIs, els_range:compare(R, VarRange)] of
+          []        -> {0, 0}; % Beginning of document
+          FunRanges -> maps:get(from, lists:last(FunRanges))
+        end,
+      %% Find beginning of first function clause after VarRange
+      To =
```
[the remark this answers is not in the document]
Comment (gomoripeti) [reply apps/els_lsp/src/els_rename_provider.erl:241]: maybe a better idea is for els_parser to store the full range of a function clause in the `function_clause` POI data

File: apps/els_lsp/src/els_rename_provider.erl (hunk 1 above)
Comment (plux) [reply apps/els_lsp/src/els_rename_provider.erl:227]: Good points, I will add support for other top-level forms as well. 
The reason for the currently implemented logic is that function_clause ranges don't contain the beginning and the end of the body of the clause, but rather just the function clause head.

File: apps/els_lsp/src/els_rename_provider.erl (hunk 2 above)
[the remark this answers is not in the document]
Comment (plux) [reply apps/els_lsp/src/els_rename_provider.erl:241]: Good point, I will see if I can implement an upper bound using the function wrapping_range.
If `els_parser` could return the full range of the function_clause that would make the implementation of this functionality cleaner, not sure how tricky it is to implement in `els_parser`..

File: apps/els_lsp/priv/code_navigation/src/rename_variable.erl [hunk 3]
```diff
@@ -10,3 +10,23 @@ foo(_Var) ->
...
   Var.
+
+-spec baz(Var) -> Var
+          when Var :: atom().
+baz(Var) ->
+  Var.
+
+-record(foo, {a :: Var,
+              b :: [Var]}).
+%% BUG: `Var' in MACRO(`Var') is not considered a variable POI
```
Comment (gomoripeti) [inline apps/els_lsp/priv/code_navigation/src/rename_variable.erl:21]: thanks for finding this bug, indeed els_parser currently does not expect sub-POIs in the define name, so it does not recurse into it ([els_parser:attribute_subtrees](https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_parser.erl#L972))

Comment (robertoaloi) [reply apps/els_lsp/priv/code_navigation/src/rename_variable.erl:21]: Should we file a ticket about this?

**Review by robertoaloi — APPROVED** [review]
To me this looks like a very good step forward. I think we can merge this in and eventually improve it later. Thanks @plux !
