### PR TITLE
Fix parsing trailing comments in modules

### LINKED ISSUE #1171: els_parser:parse_form/1 fails on lists:last
I am not sure if this is proper way to report errors, but is is what I get in the logs a lot:

[2022-01-11T15:39:40.022731+01:00] [warning] Please report error parsing form error:function_clause:[{lists,last,[[]],[{file,"lists.erl"},{line,228}]},{els_parser,ensure_dot,1,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,144}]},{els_parser,parse_form,1,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,85}]},{els_parser,'-parse_forms/1-lc$^0/1-0-',1,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,74}]},{els_parser,'-parse_forms/1-lc$^0/1-0-',1,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,80}]},{els_parser,parse,1,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,33}]},{els_dt_document,new,4,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_dt_document.erl"},{line,143}]},{els_indexing,index,3,[{file,"~/projects/erlang/erlang_ls/apps/els_lsp/src/els_indexing.erl"},{line,63}]}], {raw_string,#{end_location => {205,79},location => {205,1}},"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"} [els_parser:parse_forms/1 L76] <0.180.0>

### PR DESCRIPTION
**Pull request by gomoripeti**
erlfmt_parser returns a `raw_string` form for comments which are after the last
form in the file and not followed by any more form. It was not expected by
els_parser that a raw_string can contain no tokens (just comments and
whitespace). A file with no code just whitespace has the same result.

Fixes #1171

### CODE REVIEW

File: apps/els_lsp/test/els_parser_SUITE.erl [hunk 1]
```diff
@@ -104,6 +105,28 @@ parse_incomplete_spec(_Config) ->
...
+%% Issue #1171
+parse_no_tokens(_Config) ->
+  %% scanning text containing only whitespaces returns an empty list of tokens,
+  %% which used to crash els_parser
+  Text1 = "  \n  ",
+  {ok, []} = els_parser:parse(Text1),
+  %% `els_parser:parse' actually catches the exception and only prints a warning
+  %% log. In order to make sure there is no crash, we need to call an internal
+  %% debug function that would really crash and make the test case fail
+  error = els_parser:parse_incomplete_text(Text1, {1, 1}),
```
Comment (gomoripeti) [inline apps/els_lsp/test/els_parser_SUITE.erl:117]: I wonder if there is a better way to make sure no warning log is emitted in ct tests?

Comment (robertoaloi) [reply apps/els_lsp/test/els_parser_SUITE.erl:117]: Not sure I'm following 100%, but an option could be to (eventually isolate and) mock with passthrough the function generating the warning and check from CT if the function was called via `meck_history` or similar.

**Review by robertoaloi — APPROVED** [review]

File: apps/els_lsp/test/els_parser_SUITE.erl (hunk 1 above)
Comment (gomoripeti) [reply apps/els_lsp/test/els_parser_SUITE.erl:117]: good idea

**Comment by robertoaloi** [comment]
I will merge this now, given it causes crashes. Feel free to provide the CT change as a follow up. Thanks for fixing this!
