### PR TITLE
Fix crash when applying edits to unicode text

### LINKED ISSUE #1039: els_index_buffer crashed while applying edits
**Describe the bug**
`els_index_buffer` creashed while applying edits.I think it's a coding problem as shown below.

increment

**To Reproduce**
erlang_ls.config : `incremental_sync: true`
file encoding: `UTF-8`
code:

```erlang
-module(test).

-export([test/0]).

%% 英文 edit this line
test() ->
    ok.
```

**Log**
[Error - 上午11:40:50] [2021-06-15T11:40:50.557000+08:00] [error] [els_index_buffer] Crashed while applying edits <<"file:///c%3A/Users/miSaki/Desktop/test/src/test.erl">>: {error,badarg,[{erlang,iolist_to_binary,[[<<"-module(test).\r">>,"\n",<<"\r">>,"\n",<<"-export([test/0]).\r">>,"\n",<<"\r">>,"\n",[37,37,32,33521,25991,13],"\n",<<"test() ->\r">>,"\n",<<"    ok.">>]],[]},{els_text,lines_to_bin,1,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/apps/els_core/src/els_text.erl"},{line,106}]},{els_index_buffer,do_apply_edits,2,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/apps/els_lsp/src/els_index_buffer.erl"},{line,82}]},{els_index_buffer,loop,0,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/apps/els_lsp/src/els_index_buffer.erl"},{line,60}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,234}]}]} [els_index_buffer:loop/0 L62] <0.182.0>

**Context**
 - `erlang_ls` version (tag/sha): 0.17.0
 - Editor used: VSCode  1.57.0
 - LSP client used: erlang-ls.erlang-ls v0.0.27

### PR DESCRIPTION
**Pull request by plux**
### Description

Use `els_utils:to_binary/1` instead of `iolist_to_binary/1` to ensure proper unicode handling when applying text edits.

Fixes #1039

### CODE REVIEW

File: apps/els_lsp/test/els_text_SUITE.erl [hunk 1]
```diff
@@ -150,3 +151,15 @@ apply_edits_multi_line(_Config) ->
...
+
+apply_edits_unicode(_Config) ->
+  In = <<"二郎"/utf8>>,
+  C = fun(FromC, ToC, Str) -> {#{from => {0, FromC}, to => {0, ToC}}, Str} end,
+  F = fun els_text:apply_edits/2,
+  ?assertEqual(<<"㇐郎"/utf8>>, F(In, [C(0, 1, "㇐")])),
+  ?assertEqual(<<"二㇐郎"/utf8>>, F(In, [C(1, 1, "㇐")])),
+  ?assertEqual(<<"二㇐"/utf8>>, F(In, [C(1, 2, "㇐")])),
+  ?assertEqual(<<"二郎㇐"/utf8>>, F(In, [C(2, 2, "㇐")])),
+  ?assertEqual(<<"二郎㇐"/utf8>>, F(In, [C(2, 2, "㇐")])),
```
Comment (robertoaloi) [inline apps/els_lsp/test/els_text_SUITE.erl:163]: Nit: this seems repeated?

**Review by robertoaloi — APPROVED** [review]

**Comment by robertoaloi** [comment]
Thanks!
