### PR TITLE
[#196] Completion returns function/arity when in export list

### LINKED ISSUE #196: Function names in the export entry list are not completed correctly
**Describe the bug**
Function names typed in the export entry list are not completed correctly.

**To Reproduce**
Add an entry to an export list. The list of completions appears showing functions in the format `name/arity`.

**Expected behavior**
When pressing ENTER `name/arity` is inserted.

**Actual behavior**
When pressing ENTER `name()` is inserted.

**Context**
 - `erlang_ls` version (tag/sha): 
 - Editor used: Emacs
 - LSP client used:

### PR DESCRIPTION
**Pull request by jfacorro**
### Description

Completion returns function/arity when in export list.

Fixes #196.

### CODE REVIEW

File: src/els_parser.erl [hunk 1]
```diff
@@ -56,7 +56,7 @@ parse_form(IoDevice, Location0, Parser, _Options) ->
           {ok, POIs, Location1}
       catch
         _:_ ->
-          {ok, [], Location1}
+          {ok, find_attribute_tokens(Tokens), Location1}
```
Comment (jfacorro) [inline src/els_parser.erl]: This is to handle the case when there is a syntax error in the export list, because an entry is not yet written but we still need the information about the section as one of the POIs.

```
-export([ foo/1
        ,  b
        ]).
```
```
